apiVersion: apps/v1
kind: Deployment
metadata:
  name: alerta-next-backend
spec:
  template:
    spec:
      containers:
        - name: backend
          env:
            - name: OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: alerta-next-oidc
                  key: client-secret
